## 1. 测试CUDA是否可用

In [ ]:
import torch

print(torch.__version__)
print("gpu", torch.cuda.is_available())

## 2. 字符串测试

In [ ]:
url = "https://zaojv.com/4420198.html"
urll = url[0:-5]
urlr = url[-5:]
print(urll)
print(urlr)

## 2. 测试正则表达式

In [ ]:
import re

def delChars(sentence):
    
    sentence = re.sub(r'^(（)*(\()*', "", sentence)
    sentence = sentence.strip()
    sentence = re.sub(r'^(\d+)*(\.)*(\))*(）)*(、)*', "", sentence)
    sentence = re.sub('(\d+)*([a-zA-Z]+)', "", sentence)
    sentence = sentence.strip()
    sentence = re.sub('(,)+', "，", sentence)
    return sentence

sentence = "(1) 这些玻璃工ASFJKDSHFH艺品玲珑asdfaadfa剔透,令人爱不释手。"
sentence = delChars(sentence)
print(sentence)

In [ ]:
import re
sentence = "刁迈彭一面让他起，一面故意做出～的样子，说‘这是怎么好！这是怎么好！叫我怎么对得起死的大哥！’★李宝嘉《官场现形记》第五十一回"
sentence = re.sub('(★.*)+', "", sentence)
print(sentence)

## 3. 测试循环

In [ ]:
cy = ['爱不释手', '奇葩异卉', '山清水秀', '美不胜收', '望而生畏']
for cyi in range(0, len(cy) - 1):
    for cyj in range(cyi + 1, len(cy)):
        print(str(cyi) + str(cyj))
        print(cy[cyi] + " " + cy[cyj])

In [ ]:
datalist = []
cy = ['爱不释手', '奇葩异卉', '山清水秀', '美不胜收', '望而生畏']
for cyi in range(0, len(cy) - 1):
    for cyj in range(cyi + 1, len(cy)):
        data = []
        data.append(cy[cyi])
        data.append(cy[cyj])
        data.append(sentence)
#         print(data)
        datalist.append(data)
cy = ['爱不释手2', '奇葩异卉2', '山清水秀2', '美不胜收2', '望而生畏2']
for cyi in range(0, len(cy) - 1):
    for cyj in range(cyi + 1, len(cy)):
        data = []
        data.append(cy[cyi])
        data.append(cy[cyj])
        data.append(sentence)
#         print(data)
        datalist.append(data)
print(datalist)

## 4. 测试字符串列表去重

In [ ]:
cy_set = set({"爱不释手奇葩异卉"})
tmp_set = set({"爱不释手美不胜收"})
# cy_set = cy_set | tmp_set # 并集
cy_set = cy_set & tmp_set # 交集
print(cy_set)
print(cy_set == set())
print(len(cy_set))

In [ ]:
all_set = set()
subdata_i = ['哀兵必胜', '骄兵必败', '有句话叫做骄兵必败，哀兵必胜。虽然我们队赢了这场比赛，但我们不能骄傲，否则下次输的一方一定是我们。']
strcat1 = {subdata_i[0] + subdata_i[1]}
strcat2 = {subdata_i[1] + subdata_i[0]}
print(strcat1)
print(strcat2)
all_set |= strcat1
all_set |= strcat2
print(all_set)

## 5. 测试写csv文件
pandas

In [ ]:
import pandas as pd

#任意的多组列表
a = [1,2,3]
b = [4,5,6]    

#字典中的key值即为csv中列名
dataframe = pd.DataFrame({'a_name':a,'b_name':b})
，,
#将DataFrame存储为csv,index表示是否显示行名，default=True
dataframe.to_csv("test.csv",index=True,sep=',')

In [ ]:
import pandas as pd

a = [[1, 2, 3],[2, 3, 4],[3, 4, 5]]
a1 = pd.DataFrame(a)
a1.to_csv('test.csv',mode='a', index=False,header=["成语1", "成语2", "造句"])

---
csv

In [ ]:
import csv

#python2可以用file替代open
with open("test.csv","a", newline = "") as csvfile: 
    writer = csv.writer(csvfile)

    #先写入columns_name
    writer.writerow(["index","a_name","b_name"])
    #写入多行用writerows
    writer.writerows([[0,1,3],[1,2,3],[2,3,4]])

## 6. 测试读csv文件

In [ ]:
import pandas as pd
# data = pd.read_csv('DataCrawler/MyData/Data_1.csv')
# print(data)

计算爬取的总数据量（条）:

In [ ]:
filepath = "DataCrawler/MyData/Data_.csv"
tot_len = 0
for i in range(1, 29):
    pathl = filepath[0:-4]
    pathr = filepath[-4:]
    nowpath = pathl + str(i) + pathr
    # print(nowpath)
    data = pd.read_csv(nowpath)
    tot_len += len(data)
    print(data)
print(tot_len)

In [ ]:
filepath = "1.csv"
data = pd.read_csv(filepath)
print(data)

## 8. 测试清理脏数据

In [ ]:
subPageData = [['爱不释dsfa', '奇葩异卉', '这些玻璃工艺品玲珑剔透，令人爱不释手。'],['爱不释手', '奇葩异卉', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手', '山清水秀', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手', '美不胜收', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手', '望而生畏', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉', '山清水秀', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉', '美不胜收', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉', '望而生畏', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['山清水秀', '美不胜收', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['山清水秀', '望而生畏', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['美不胜收', '望而生畏', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手2', '奇葩异卉2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手2', '山清水秀2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手2', '美不胜收2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['爱不释手2', '望而生畏2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉2', '山清水秀2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉2', '美不胜收2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['奇葩异卉2', '望而生畏2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['山清水秀2', '美不胜收2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['山清水秀2', '望而生畏2', '这些玻璃工艺品玲珑剔透，令人爱不释手。'], ['美不胜收2', '望而生畏2', '这些玻璃工艺品玲珑剔透，令人爱不释手。']]
datalist = []
for subdata_i in subPageData:
    if len(subdata_i[0]) < 4 or len(subdata_i[1]) < 4:
        continue
    datalist.append(subdata_i)
print(len(datalist))

## 9. 使用pandas将csv文件转成xlsx文件

In [ ]:
import pandas as pd
def csv_to_xlsx_pd():
    csv = pd.read_csv('DataCrawler/MyData/Data_4.csv', encoding='utf-8')
    csv.to_excel('1.xlsx', sheet_name='data', index = False, header = None)
csv_to_xlsx_pd()

## 10. 使用第三方库pandas将xlsx文件转csv文件

In [ ]:
import pandas as pd

def xlsx_to_csv_pd():
    data_xls = pd.read_excel('1.xlsx', index_col=0)
    data_xls.to_csv('1.csv', encoding='utf-8')

xlsx_to_csv_pd()

## 11. 测试json、python dict

In [7]:
import json

idiomDict = {}
# 读取test.json中的数据
with open('test.json', 'r',encoding="utf-8") as f1:
    list1 = f1.readlines()[0]
    preData = json.loads(list1)
    for data in preData:
        word = data["word"]
#         print(data["explanation"])
#         print(data["example"])
        idiomDict[word] = {}
        idiomDict[word]["explanation"] = data["explanation"]
        idiomDict[word]["example"] = data["example"]

print(idiomDict)
print(type(idiomDict))
print(list(idiomDict.keys()))

{'阿鼻地狱': {'explanation': '阿鼻梵语的译音，意译为无间”，即痛苦无有间断之意。常用来比喻黑暗的社会和严酷的牢狱。又比喻无法摆脱的极其痛苦的境地。', 'example': '但也有少数意志薄弱的……逐步上当，终至堕入～。★《上饶集中营·炼狱杂记》'}, '阿党比周': {'explanation': '指相互勾结，相互偏袒，结党营私。', 'example': '《论语·卫灵公》众恶之，必察焉；众好之，必察焉”何晏集解引三国魏王肃曰或众～，或其人特立不群，故好恶不可不察也。”'}, '阿党相为': {'explanation': '阿党偏袒、偏私一方。为了谋求私利相互偏袒、包庇。', 'example': '无'}, '阿狗阿猫': {'explanation': '旧时人们常用的小名。引申为任何轻贱的，不值得重视的人或著作。', 'example': '无'}, '阿姑阿翁': {'explanation': '阿名词的前缀。姑丈夫的母亲。翁丈夫的父亲。指公公婆婆。', 'example': '既然如此，你我两个，便学个不痴不聋的～。★《儿女英雄传》二三回'}}
<class 'dict'>
['阿鼻地狱', '阿党比周', '阿党相为', '阿狗阿猫', '阿姑阿翁']


## 12. 测试CrossEntropyLoss

In [6]:
import torch
import torch.nn as nn

model = nn.Linear(10, 3)
criterion = nn.CrossEntropyLoss()

x = torch.randn(16, 10)
# print(x)
y = torch.randint(0, 3, size=(16,))  # (16, )
print(y)
logits = model(x)  # (16, 3)
print(logits)
loss = criterion(logits, y)
print(loss)

tensor([2, 1, 2, 0, 2, 1, 1, 1, 0, 0, 1, 2, 1, 2, 1, 2])
tensor([[ 0.4870,  2.0264,  1.9457],
        [-0.8106, -0.4189, -0.2331],
        [ 0.8117,  0.1031, -0.5369],
        [-0.4613, -0.1268, -0.0186],
        [ 0.6888,  0.2111,  0.1638],
        [ 0.0987,  1.4254,  0.1458],
        [ 0.2610,  0.9352,  1.7628],
        [-0.6567, -0.1876, -0.4520],
        [ 0.2947,  0.2893, -0.6391],
        [ 1.2170,  0.7614, -0.4177],
        [-0.6920, -0.4242, -0.1227],
        [ 1.7133,  0.3522, -0.9335],
        [-0.3449, -0.6127, -0.8734],
        [ 0.0263, -0.1226, -0.7970],
        [ 0.6767,  2.1075, -0.9630],
        [-0.2614, -0.3616,  0.8290]], grad_fn=<AddmmBackward>)
tensor(1.1381, grad_fn=<NllLossBackward>)


## 查看训练日志文件
* 获取train_loss 用于ECHARTS折线图的data

In [6]:
import pandas as pd
import numpy as np
data = pd.read_pickle('IdiomBertModel/state_dict/multi__state_dict/df_log.pickle')
print(data)
np.array(data.train_loss.values)

   epoch  train_loss  train_acc test_loss  test_acc
0      0    1.037369   0.464894  1.033418  0.502797
1      1    0.999544   0.499818  1.027154  0.503954
2      2    0.991576   0.503632  1.026418  0.506654
3      3    0.987847   0.502946  1.024737  0.509547
4      4    0.985253   0.504553  1.022145  0.509932
5      5    0.982536   0.505903  1.019545  0.511475
6      6    0.979560   0.508238  1.016818  0.512247
7      7    0.977170   0.509995  1.013082  0.513211
8      8    0.974004   0.509502  1.010937  0.514176
9      9    0.971730   0.511795  1.007149  0.517454
10    10    0.968525   0.513873  1.001709  0.518419
11    11    0.965949   0.514944  0.998334  0.521311
12    12    0.962778   0.517237  0.994096  0.522469
13    13    0.960138   0.518030  0.988279  0.524783
14    14    0.957496   0.518672  0.983799  0.526712
15    15    0.954009   0.522786  0.979218   0.52864
16    16    0.950479   0.523900  0.974493  0.530955
17    17    0.948693   0.523600  0.971217  0.530955
18    18    

array([1.0373688 , 0.99954391, 0.99157605, 0.98784667, 0.98525307,
       0.98253595, 0.9795602 , 0.97716979, 0.97400375, 0.9717297 ,
       0.96852497, 0.96594896, 0.96277808, 0.96013765, 0.95749585,
       0.95400866, 0.95047928, 0.94869281, 0.94654232, 0.94384885,
       0.94037837, 0.9404654 , 0.93891471, 0.93619817, 0.93507252,
       0.9339158 , 0.93241709, 0.93136947, 0.93092031, 0.92868649,
       0.92832957, 0.92697858, 0.9269564 , 0.92483477, 0.92520076,
       0.92430654, 0.92382296, 0.92351595, 0.92368185, 0.92206069,
       0.92183608, 0.92243669, 0.92140265, 0.92124816, 0.919753  ,
       0.9197892 , 0.91907641, 0.91991825, 0.91937882, 0.91795984,
       0.9183317 , 0.91937876, 0.91783003, 0.91867194, 0.91816645,
       0.91813608, 0.91858871])

* 获取epoch用于ECHARTS折线图的xAxis

In [11]:
xAxis = np.array(data.epoch.values)
for i, x in enumerate(xAxis):
    xAxis[i] = 'epoch' + str(x)
print(xAxis)    
print(np.array(xAxis))

['epoch0' 'epoch1' 'epoch2' 'epoch3' 'epoch4' 'epoch5' 'epoch6' 'epoch7'
 'epoch8' 'epoch9' 'epoch10' 'epoch11' 'epoch12' 'epoch13' 'epoch14'
 'epoch15' 'epoch16' 'epoch17' 'epoch18' 'epoch19' 'epoch20' 'epoch21'
 'epoch22' 'epoch23' 'epoch24' 'epoch25' 'epoch26' 'epoch27' 'epoch28'
 'epoch29' 'epoch30' 'epoch31' 'epoch32' 'epoch33' 'epoch34' 'epoch35'
 'epoch36' 'epoch37' 'epoch38' 'epoch39' 'epoch40' 'epoch41' 'epoch42'
 'epoch43' 'epoch44' 'epoch45' 'epoch46' 'epoch47' 'epoch48' 'epoch49'
 'epoch50' 'epoch51' 'epoch52' 'epoch53' 'epoch54' 'epoch55' 'epoch56']
['epoch0' 'epoch1' 'epoch2' 'epoch3' 'epoch4' 'epoch5' 'epoch6' 'epoch7'
 'epoch8' 'epoch9' 'epoch10' 'epoch11' 'epoch12' 'epoch13' 'epoch14'
 'epoch15' 'epoch16' 'epoch17' 'epoch18' 'epoch19' 'epoch20' 'epoch21'
 'epoch22' 'epoch23' 'epoch24' 'epoch25' 'epoch26' 'epoch27' 'epoch28'
 'epoch29' 'epoch30' 'epoch31' 'epoch32' 'epoch33' 'epoch34' 'epoch35'
 'epoch36' 'epoch37' 'epoch38' 'epoch39' 'epoch40' 'epoch41' 'epoch42'
 'epo